#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
    -H "Content-Type: application/json" \
    -d '{
        "title": "I accidentally told my boss kid Santa was not real and it turned into the weirdest promotion of my life",
        "type": "story",
        "story": "So this happened last December and it still feels like a fever dream. I am 26 and work in a mid-sized marketing firm. Low on the ladder, not an intern, but definitely not a corner office guy. Around the holidays the company throws this super fancy Christmas party at the CEO house. He is very into family culture so we all show up with spouses, kids, dogs, emotional baggage, all of it. Now I do not have kids. I barely have matching socks most days. But I love Christmas and I am decent with kids. So when my boss Mike asked me to help watch over the kid area while the adults got wine-drunk on spiced cabernet I said sure. Free cookies and no small talk about quarterly reports. Count me in. I am helping a group of kids decorate sugar cookies when this little boy, maybe 6 or 7, looks up at me and goes, Do you think Santa is really real. I did not even think. Not for a second. I said, Nah, but it is fun to pretend right. Just like that. Friendly tone, dumb grin, sprinkle-covered fingers. This kid face drops like I told him his goldfish died again. Full-on trembling lip. I immediately realize I have made a terrible career-altering mistake. Guess who the kid was. Mike son. Of course. Ten minutes later I am summoned. Not by HR. Not by my manager. By Mike himself. I am picturing my career in flames. Me, jobless in January, selling feet pics to pay rent. But instead he sits me down, deadpan serious, and says, You told my son the truth. Nobody in this company tells the truth. They all smile and nod and fake-believe in Santa. You, you just blurt it out. You do not overthink. I like that. I am sitting there stunned. He continues, I need someone like that on the innovation team. We are pitching bold ideas this year. No BS. Long story short, I got promoted. Literally because I ruined a kid Christmas. Mike later told me his son was already suspicious and I just accelerated the timeline. His wife was apparently furious for a week. Now I am on a team I never thought I would be on because I killed Santa. Every time I walk into a meeting my coworkers whisper Saint Nick Slayer under their breath. That is the story of how I accidentally Grinched my way up the corporate ladder. Life is weird."
    }'
