#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
    -H "Content-Type: application/json" \
    -d '{
        "title": "I accidentally confessed to the wrong girl. Three years later she is my wife.",
        "type": "story",
        "story": "This happened back in 2019 and even now I sometimes look at her across the room and think, how on earth did we end up here. Back in university I was hopelessly in love with a girl from one of my classes. We had a few lectures together, ended up in the same project group once, and slowly built one of those flirty friendships where you are never quite sure if it means something more. My friends were convinced she liked me. Dude she is into you, they kept saying. Just tell her already. After weeks of overthinking every possible outcome I finally worked up the courage. One evening sitting on my bed with my heart pounding I typed out a long message. Not overly dramatic but honest enough to say what I felt. My hands were literally shaking while I typed. I reread it about twenty times. Then I hit send. A few seconds later my stomach dropped. I had sent it to the wrong girl. Turns out I had two people with the same name in my contacts. One was my crush from class. The other was someone I had met briefly at a random campus event months earlier and barely remembered. Guess which one received my heartfelt confession. Panic hit instantly. I considered unsending it but it was too late. She had already seen it. About a minute later my phone buzzed. Her reply said something like, Wow I definitely was not expecting that. But hey do you maybe want to grab coffee and laugh about this accidental confession. I genuinely considered never replying and disappearing forever. But the embarrassment had already happened so I figured I might as well face it. Worst case scenario we would laugh about it once and never talk again. So we met up for coffee. And we did laugh. A lot. But somewhere between the jokes and awkward explanations I realized something unexpected. She was incredible. Sarcastic, thoughtful, weirdly insightful, and effortlessly kind in a way that immediately made me feel comfortable. We kept hanging out after that. At first it was mostly as a running joke. We called ourselves the accidental couple. But somewhere along the way the joke stopped feeling like a joke. The feelings grew slowly and naturally. And for the first time I did not feel anxious or confused about whether someone liked me back. Being with her was just easy. Fast forward to 2022. I proposed to her. This time very intentionally. We got married last year and sometimes when people ask how we met I tell them the truth. I accidentally confessed my love to the wrong girl. But somehow I ended up with exactly the right one."
    }'
