#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
    -H "Content-Type: application/json" \
    -d '{
        "title": "I accidentally pooped in my best friends mug and did not tell her",
        "type": "story",
        "story": "Okay I genuinely cannot believe I am typing this and I am already mortified so please be gentle. I am 20 and I went on a road trip to Arizona with my best friend. We have been best friends for like 7 years, basically family. The trip was honestly amazing, one of the best we ever had. Nothing weird or bad happened the whole time. On our way back we stayed at this super cute Americana themed hotel in Flagstaff. Jane loved it so much and would not stop talking about it so my dad bought her a mug from the gift shop. She was really excited about it and kept it packed safely so it would not break. When we got back to my house in Chicago, Jane took the mug out while reorganizing her suitcase and left it on my nightstand for a bit. That night I had really bad stomach issues. I have anxiety and IBS and traveling messes me up badly. The bathroom was occupied and I panicked. I saw the mug and made the worst decision of my life. I used it. I immediately knew it was disgusting and wrong. I told myself I would clean it properly right away. I rinsed it with water and wiped it out but I did not fully wash it yet. Jane came back into the room sooner than I expected and I freaked out and put it back thinking I would deal with it later. She packed it up and left before I got another chance. I convinced myself it was fine. I told myself I rinsed it enough. I told myself it probably would not smell. I was wrong. A couple days later she called me saying her suitcase smelled awful and that there was dried brown stuff on the mug. When she said that I completely froze. I did not know what to say. I just acted confused and said that is so weird and let the conversation end. I hate myself for that. After that I completely broke down. I cried for hours. My dad noticed and asked what was wrong and I could not even bring myself to explain it. I felt disgusting and guilty and like I ruined something meaningful over a moment of panic. Jane was really kind to me afterward. She called me later and comforted me even though she had no idea what was actually going on. We watched shows together on the phone like everything was normal and that somehow made it worse. Now I do not know what to do. I do not know if I should tell her. I do not know if she already knows and is just being nice. I do not know if confessing would permanently ruin our friendship or if not telling her is worse. I feel sick every time I think about it. I know it was gross. I know there is no excuse. I just do not know how to fix this or live with the guilt."
    }'
