#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
  -H "Content-Type: application/json" \
  -d '{
    "title": "I ended up in my neighbors will",
    "type": "story",
    "story": "A few months ago, I moved into a new apartment building. First time living alone. First time realizing I have no idea how to cook rice without Googling it. Anyway, my neighbor across the hall is an older lady named Mrs. Kaplan. She walks with a cane that has a tiny built-in flashlight, and wears a robe with embroidered cats on it. Big grandma energy. One day, I helped her carry her groceries up the stairs because the elevator was broken. She gave me a butterscotch candy and said, you are a good boy, just like my grandson. I thought she was being sweet and nostalgic. Nope. She started calling me Ben. My name is not Ben. But every time I corrected her, she just squinted at me and went, do not be difficult, Ben. So I gave up. I became Ben. She would knock on my door with Tupperware full of mysterious casseroles and say things like, eat this, you are too skinny, Ben was too skinny too. I figured hey, free food, who am I to argue. Fast forward, one day she invites me to a family dinner. I assume it is just her and maybe a cat. Nope. I walk in, and half her actual family is there. They stare at me like, who is this guy. And she proudly announces, everyone, this is Ben, he is back from Tokyo. Now I am locked into this insane roleplay where I apparently lived in Tokyo, work in tech, and still play the trumpet. I have not touched a trumpet since middle school band, but I nod and smile like I am auditioning for a Netflix series. Here is the twist, she knows. She later pulled me aside and said, I know you are not Ben, but I like having you around. Last week, she called me over to help fix her TV, and offhandedly mentioned, you will take the cat figurines when I am gone, right, I already put it in the will. So now I am inheriting cat figurines. Because I became someone else is grandson by accident. And honestly, I think Ben would have wanted it that way."
  }'
