#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
    -H "Content-Type: application/json" \
    -d '{
        "title": "I told my best friend I loved her in a tiny dorm room over instant noodles. She said took you long enough.",
        "type": "story",
        "story": "Back in college I had this best friend Anna. We did everything together. Late night study sessions, pizza runs, movie marathons, you name it. Everyone kept asking if we were dating but we always laughed it off. No we are just friends we would say. Except I was not just friends. At least not in my head. Every time she laughed at one of my dumb jokes or fell asleep on my shoulder during a movie my heart reminded me that I was completely gone for her. But I never said anything because I did not want to ruin what we had. Fast forward to one rainy Friday night. We were hanging out in my tiny dorm room eating instant noodles because we were broke students. She was sitting on my bed scrolling through her phone and I was half watching the rain hit the window. And then out of nowhere she sighed and said, you know I wonder if I will ever find someone who actually gets me. My brain short circuited. Before I could stop myself I blurted out, I get you. She looked up. What. At this point I should have laughed it off. But apparently my mouth decided it was now or never because I just kept going. I mean I get you. I know how you take your coffee. I know you hate when people talk during movies. I know you secretly cry at Pixar films. And I know you act tough but you are the kindest person I have ever met. I get you Anna. And I think I love you. Silence. The kind of silence that makes you want to crawl under the bed and never come out. She just stared at me and I was about to backtrack and say haha just kidding anyway let us watch Toy Story. But then she smiled. Not the small polite smile she gave strangers but the big smile, the one that crinkled her nose and made her eyes light up. She put her phone down, scooted closer, and whispered, took you long enough. Then she kissed me. Right there in my crappy dorm room with rain tapping on the window and two half eaten cups of noodles on the desk. We have been together ever since."
    }'
