#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
  -H "Content-Type: application/json" \
  -d '{
    "title": "Sir, I have a report to make.",
    "type": "story",
    "story": "This is not a report I wish to make, I said into a microrecorder that would eventually broadcast the contents offworld, hopefully once I was far enough away. Humans have learned how to triangulate and jam radio signals, I continued, as is standard for every starfaring race, but I did not expect such a capacity from a non starfaring species. That is not even the worst of it. They have built these massive versions of themselves. They call them mecha, and they are as tall as a hab block and packing at least half the firepower of our battleships, with some exceptional ones packing more. I went into reconnaissance of undeveloped alien worlds because I wanted to avoid this kind of situation. I could tell my heart rate was spiking. In and out. In and out. I will film a video that I shall attach to this message, I said, pointing the lens of my recording device at the back of something whose very outline screamed it was death incarnate. And then rounds the size of battleship shells shook the building I had set up in. I was showered by sprinklers. But I had to record this. No, they were not onto me. I and the entire building were just collateral damage from shots fired by another mecha that had missed the one whose back I had been filming. This is what I am talking about, I nearly screamed into my microrecorder as I managed to get it focused back on the two titans shooting at each other. I need an immediate extraction. But since I know this will not be transmitted for several hours, I will be filming as much of this as I can, as per my mission. Shell casings large enough to crush cars rocketed out of the sides of their guns. These are the war machines every human country that can afford them is using. There are tens of thousands of these things on their planet, maybe even more. One of them threw the other through half a block of buildings once they closed to grappling range. Then tried gunning it down but it dodged and the shots went wild causing even more collateral damage. I highly suggest that we do not discount humans because they are not a starfaring species. Not only have they developed this technology to kill each other, but they have an astounding ability to come together against what they perceive as a greater threat despite all differences. Even during their latest nuclear Cold War, the leaders of the two factions explicitly agreed that if space aliens invaded they would team up to fight them. And if this is how they fight each other, I really do not want to see how they would fight us. Now I needed to place my microrecorder somewhere it could transmit all this offworld. Then get the hell away from it before any humans found it."
  }'
