#!/bin/bash

curl -X POST "http://localhost:8000/generate-video" \
  -H "Content-Type: application/json" \
  -d '{
    "title": "The Tape That Married My Grandpa",
    "type": "story",
    "story": "I was 19 when I found the cassette tape in my grandpa s attic, labeled do not play 1993 in his shaky handwriting. He had passed two years earlier and mom finally let me sort through his old things. The tape was wedged inside an old Walkman, batteries long dead. My curiosity won. I swapped in fresh batteries and hit play in the dark. Static. Then his voice, younger than I had ever heard. If you are listening kid, you are probably me in forty years, or someone I love. Either way, listen close. He talked for twelve minutes straight, no pauses, like he had rehearsed it a hundred times. Said he had buried a metal box under the big maple behind the house, exactly 47 paces from the back porch. Inside was a Polaroid of him and grandma on their first date, a silver dollar from 1943, and a letter addressed to future me. The kicker? He recorded this the night before he proposed, convinced he would chicken out and need a push from his older self. I laughed so hard I cried. Then I grabbed a shovel. The ground was frozen, late November, but I chipped away until the blade clanged on metal. The box was rusted shut. Inside was the photo, grandma mid laugh with wind in her hair, the coin still shiny, and the letter. Yellowed paper, ink faded but legible. It was not addressed to him. It was addressed to me. Dear grandkid, yeah you. If you found this I did not wuss out. I asked her. She said yes. We are probably dancing in the kitchen right now to that awful Sinatra record. Do not let anyone tell you love is a risk. It is the only bet worth rigging. Plant something here when the tree dies. Keep the chain going. PS, tell your mom the meatloaf recipe is on the back of this page. She will pretend she hates it. She really does not. I read it twice. Then I looked up. Mom was in the doorway, eyes wet, holding the Walkman. She flipped the letter over. Grandma s meatloaf in grandpa s handwriting, complete with extra Worcestershire or else. We made it that night. Burnt the edges, just like he used to. The maple is still standing. I planted tulip bulbs last spring. They are poking through the dirt now, stubborn little green spears. Some nights I swear I hear Sinatra drifting from the kitchen. I never check. I just smile and turn up the volume."
  }'
